# Prometheus

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: mcp
    metrics_path: /metrics
    static_configs:
      - targets: ['mcp-production:9090']
        labels:
          env: production
      - targets: ['mcp-development:9090']
        labels:
          env: development

  - job_name: traefik
    static_configs:
      - targets: ['traefik:8082']
        labels:
          env: production
